<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>callrift</AssemblyName>
    <RootNamespace>Callrift.Cli</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Callrift.Core/Callrift.Core.csproj" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
