<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Callrift.Core/Callrift.Core.csproj" />
    <ProjectReference Include="../../src/Callrift.Cli/Callrift.Cli.csproj" />
    <ProjectReference Include="../Callrift.BenchmarkHook/Callrift.BenchmarkHook.csproj" />
    <ProjectReference Include="../../tools/Callrift.RealWorldCases/Callrift.RealWorldCases.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Locator" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
</Project>
