<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Callrift.Core/Callrift.Core.csproj" />
    <ProjectReference Include="../../src/Callrift.Cli/Callrift.Cli.csproj" />
    <ProjectReference Include="../../tools/Callrift.Corpus/Callrift.Corpus.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
